# Default values for vbbu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  uri: "registry.ocp4.redhat.ren:5443/ocp4/du:v1-1623-wzh-01"
  driver_uri: "registry.ocp4.redhat.ren:5443/baicell/fgpa-driver:v04"
  support_tool_uri: "registry.redhat.io/rhel8/support-tools:8.4"

service:
  nodePort: 31071

net_attach_def:
  xeth:
    name: "host-device-du"
    config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "xeth",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.160.0/24",
        "gateway": "192.168.160.254",
        "rangeStart": "192.168.160.1",
        "rangeEnd": "192.168.160.1"
      }}'
  enp:
    name: "host-device-du-ens"
    config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "enp103s0f0",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.12.0/24",
        "rangeStart": "192.168.12.105",
        "rangeEnd": "192.168.12.106"
      }}'

deploy:
  network: '[
          { "name": "host-device-du-ens",
            "interface": "veth11" },
          { "name": "host-device-du",
            "interface": "xeth" }
          ]'
  runtimeClassName: performance-wzh-performanceprofile
  cpu: 14
  memory: "64Gi"
  hugepages_1Gi: "16Gi"
  cache_memory: "16Gi"
  
  driver:
    copy_script: "tar zvxf /BaiBBU_DXSS_1.0.18--4.18.0-305.19.1.PKG --strip 1 -C /baicell/driver/ && /bin/cp -f /ocp4.install.sh /baicell/driver/ "
    load_script: "cd /baicell/driver/ && bash ./ocp4.install.sh && /bin/rm -f ./* && sleep infinity "


nodeSelector: 
  node-role.kubernetes.io/master: ""
