apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apps.baicell.com/v1alpha1",
          "kind": "VBBU",
          "metadata": {
            "name": "vbbu-sample"
          },
          "spec": {
            "affinity": {},
            "autoscaling": {
              "enabled": false,
              "maxReplicas": 100,
              "minReplicas": 1,
              "targetCPUUtilizationPercentage": 80
            },
            "fullnameOverride": "",
            "image": {
              "pullPolicy": "IfNotPresent",
              "repository": "nginx",
              "tag": ""
            },
            "imagePullSecrets": [],
            "ingress": {
              "annotations": {},
              "className": "",
              "enabled": false,
              "hosts": [
                {
                  "host": "chart-example.local",
                  "paths": [
                    {
                      "path": "/",
                      "pathType": "ImplementationSpecific"
                    }
                  ]
                }
              ],
              "tls": []
            },
            "nameOverride": "",
            "nodeSelector": {},
            "podAnnotations": {},
            "podSecurityContext": {},
            "replicaCount": 1,
            "resources": {},
            "securityContext": {},
            "service": {
              "port": 80,
              "type": "ClusterIP"
            },
            "serviceAccount": {
              "annotations": {},
              "create": true,
              "name": ""
            },
            "tolerations": []
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.10.1-ocp
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: baicell-helm-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: VBBU
      name: vbbus.apps.baicell.com
      version: v1alpha1
  description: baicell vRAN application including fpga driver, vCU, vDU
  displayName: baicell vBBU
  icon:
  - base64data: /9j/4AAQSkZJRgABAQEASABIAAD/4g0ISUNDX1BST0ZJTEUAAQEAAAz4YXBwbAIQAABtbnRyUkdCIFhZWiAH4wABAAIACgAHACRhY3NwQVBQTAAAAABBUFBMAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWFwcGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFkZXNjAAABUAAAAGJkc2NtAAABtAAAAeBjcHJ0AAADlAAAACN3dHB0AAADuAAAABRyWFlaAAADzAAAABRnWFlaAAAD4AAAABRiWFlaAAAD9AAAABRyVFJDAAAECAAACAxhYXJnAAAMFAAAACB2Y2d0AAAMNAAAADBuZGluAAAMZAAAAD5jaGFkAAAMpAAAACxtbW9kAAAM0AAAAChiVFJDAAAECAAACAxnVFJDAAAECAAACAxhYWJnAAAMFAAAACBhYWdnAAAMFAAAACBkZXNjAAAAAAAAAAhEaXNwbGF5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbWx1YwAAAAAAAAAmAAAADGhySFIAAAAIAAAB2GtvS1IAAAAIAAAB2G5iTk8AAAAIAAAB2GlkAAAAAAAIAAAB2Gh1SFUAAAAIAAAB2GNzQ1oAAAAIAAAB2GRhREsAAAAIAAAB2G5sTkwAAAAIAAAB2GZpRkkAAAAIAAAB2Gl0SVQAAAAIAAAB2GVzRVMAAAAIAAAB2HJvUk8AAAAIAAAB2GZyQ0EAAAAIAAAB2GFyAAAAAAAIAAAB2HVrVUEAAAAIAAAB2GhlSUwAAAAIAAAB2HpoVFcAAAAIAAAB2HZpVk4AAAAIAAAB2HNrU0sAAAAIAAAB2HpoQ04AAAAIAAAB2HJ1UlUAAAAIAAAB2GVuR0IAAAAIAAAB2GZyRlIAAAAIAAAB2G1zAAAAAAAIAAAB2GhpSU4AAAAIAAAB2HRoVEgAAAAIAAAB2GNhRVMAAAAIAAAB2GVuQVUAAAAIAAAB2GVzWEwAAAAIAAAB2GRlREUAAAAIAAAB2GVuVVMAAAAIAAAB2HB0QlIAAAAIAAAB2HBsUEwAAAAIAAAB2GVsR1IAAAAIAAAB2HN2U0UAAAAIAAAB2HRyVFIAAAAIAAAB2HB0UFQAAAAIAAAB2GphSlAAAAAIAAAB2ABpAE0AYQBjdGV4dAAAAABDb3B5cmlnaHQgQXBwbGUgSW5jLiwgMjAxOQAAWFlaIAAAAAAAAPDPAAEAAAABGRFYWVogAAAAAAAAhhEAAD7I////tlhZWiAAAAAAAABJcgAAscEAAAr8WFlaIAAAAAAAACdSAAAPdwAAyHtjdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADYAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8AowCoAK0AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//3BhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbdmNndAAAAAAAAAABAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAbmRpbgAAAAAAAAA2AACuAAAAUgAAAEGAAACygAAAJgAAAA5AAABPQAAAVEAAAjMzAAIzMwACMzMAAAAAAAAAAHNmMzIAAAAAAAEOqwAAByH///JvAAAJbwAA/Ef///tQ///9nAAAA9QAAL7obW1vZAAAAAAAAAYQAACuE0HttCrS/oCAAAAAAAAAAAAAAAAAAAAAAP/bAEMAAwICAwICAwMDAwQDAwQFCAUFBAQFCgcHBggMCgwMCwoLCw0OEhANDhEOCwsQFhARExQVFRUMDxcYFhQYEhQVFP/bAEMBAwQEBQQFCQUFCRQNCw0UFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFP/CABEIAMgAyAMBEQACEQEDEQH/xAAcAAEAAgIDAQAAAAAAAAAAAAAABQcEBgIDCAH/xAAbAQEAAgMBAQAAAAAAAAAAAAAABQYCAwQBB//aAAwDAQACEAMQAAAB9UgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGFr3URXL5b85T6Grd9sOUr1tzdRAAAAA+eOvzKkK9eLVmqrP9MeAAIDm76XgLpe1jonmipfTPU1x+WRWnqzdmnk8w8N0jt5ta5JOf6Y/Jz1wfN3c/ce3LGga1f5HbzW5N1L68kdvNJ7uYAQfP3UlXrv0Y54eG70ja/m3mipfTLBk69ushC1lEWfh572+4wmjts6XrFaxNl6/MrNlqxWMRZ5LdzTXRxazxyn156FtHzzvywAg+buo2vXm97HQ6Erd+27tiOHnun8Mzck9TK5irJrnLI+lLX8103hmdLj5rX+aQkNnPsnXG6NHTklu5tx7ofTeCZwte70PaPnmRnrAiNHXQ9cvg2jri+nzO0piraLGzz3zB175vfxVfEWjdO+FseVrdH1688/cblnqZVsPas/Zz7P2RdaRFmy9mm/LJQe3LEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//xAAoEAACAwACAAQFBQAAAAAAAAAEBQIDBgE1ABEUFRASFiBwEyIjMDH/2gAIAQEAAQUC/PZ3zeiRsi/ddHZKpLwzL45z2ptnf/X5+XiNsJ86gwip0gtnen+53HjhTm5cydkcC/o8+XJEf8IbhiWjFVF1EEVi1CtBDZznGuMtMsjIcmouvwW7BBmG4DPk06zP/tc6zvc30d+jXDzDZisOPsedPme8aiXyZLC4gneqr9KYTM4vEsPku1XRY/utM4mwMpx59tARhKI/TPeRgVaIpt4ZKCk9ixtJpn0PcazvTy7B8mnUcNZTXMFJ1E+bafi86fPWQpc+7g+HpFJTViZITK45XEqX8iVro7Y35zHd3Hn0TOoiu+m/Xrqrdl52Eq017WNuZJqkoVWAAIe41ne8ehll685M2NDA5IUPdwRR8W9U71n08y8fTzLwpx11lr9cwYMkoHty3WI7yi6RDp5fMKDBGujzEjrOVZ8OUeStnc4U1thCkLAGwPOnn2QVQASpkh9DTRpzSm/sUzs3yuaLbAM2cxuqr4qr/Pf/xAA2EQABBAADBAcFCAMAAAAAAAABAAIDBAUREiExNEETFCJRcYGxIDJTYZEQFSMzQnDh8CQwwf/aAAgBAwEBPwH9+4Mulbq3ZhXq0PVnkMG5Ya0OtsDguqwH9A+ixDC2Bhmg2Zcv9pa4bwsLhidUaXNB38lfY1ll7WjZn7dEnrMY+YWJACo/L+7VGZtQ6PPND3O33bUVHUnlbrYwkKSJ8LtMgyKjjdK7QwZlS1ZoRnI0hBpccghhlsjPQpInxHS8ZH7IaNicao2bFNTngGcjclV/PZ4hYhtqyZ9ywng2+fqsS4uTxTMOtSDMMU1aav8Amty9mjxMfiFifCSf3mqksYgYNQ3DmrMRnhdG05Zron9J0WW3coYmwRtjHJY3XzaJxy2LCuMZ5+ixjhD4hYZTbXiDz7xT8YrMfp2n5qaGK9Dl37isModJK4yjY31Vq9DU2P39yrW4bjTo+hVmoKt2PR7pI9Vf4WTwWE8G3z9VXhbJiUr3fpVy51UA6C5Ns1rcPaIyPIp7dLi32KPEx+IWINc+q9rRmf5XVLHwz9FRjkirtZLvVaES4jJNyb6rGLRiDI2b9/03LsXa/wAnBYawx3mtdvGfoVjHCHxCP41fscx/xOjcx2hw2qPCLT2h2wLBuzHJHzBVm7HVP4gKbicTxmxjj5K5abPNC0NIyPMZK/wsngsJ4Nvn6r/IGISPrjPLenYk2AhthpaT5+ifXrXo9WW/mpGdG8sPL2KbmssMc7dmvvCp8QL7xq/ECt4xG1umvtPesPsVa8Aa6QZnaVdn6zO6TksJvRxRmKZ2WW5PlrtxBs7XjI7/AKLE7cE1fTG/M5hYbiYgb0M27v7kLVZ3a1hXsWYGmOucz3qnbdUk1jzUV+tO33vIqbEa1dvvZ/II2nWLbZpe8eQVy9WfXe1r9pCw25XirNY9+R2rrzYLz5m7WldYp2W7XA+P8qfEq9dnYOZ7gnOL3Fx/fz//xAAuEQACAgEDAwEHAwUAAAAAAAABAgADBBESIRMxM0EUICIjMlJxEEJwBTBRYZH/2gAIAQIBAT8B/nuzXYdJj22dVeZlEiliJ1bPuMxcxi2yz+7qDMyxxcQDMYlqVJ9/IHymmJ5ljbNPi7T93w/o19aHRmiurjVTGYINWiXV2HRTCQOTPa6O26K6uNVP6PkVVnRjK767PpMu8bfiY3mWZvnMxfAsbKpXgtEtSz6D7uR4W/ExPOsuRuo3HrKXFbhiJvG3f6R3NjFjP6fZoTWZmeBpg+aZd5tfaOwi4NpXWVu+O8y8nagCespx3v5WW0PQeZVcbsdt3cTG8yzN85ljlcVAPWUUdb92kNVtL8DtFOoB9zI8LfiYpC3KTOvV9wmQyvaWTtLbCmKqf5mDSH3M34nNFv4mUQ2OSJgeaD5dnxehgYMNwjZ1IOkz+WVv9SmhrvpMOI68Fh/2UUmtLDr6TG8yzN85nyjjKtpgxTZzUdYttuO2kVtyhvcvBapgJ7Ld9s9lu+2U4LE629pk1XW2EheJj19KsLM3HZ23oIqWnGNZXmYdFiW6sJlYnUO9O86No42mY+ExO63tL6Rcu0x8a2s9pXi22HtBSK6TWsox7VtUlZlUWPaSons5sxwh4InSvqPAMqxLbT8XEA2jQfz5/8QAOxAAAgEDAQQFBg0FAAAAAAAAAQIDAAQREhMhMUEiI1FxcxQgQmGRsQUyMzRDUmJwcoGTofAQJDCCsv/aAAgBAQAGPwL7+7jRnXs2xjjnFWqm4lIZwpVnJq6ZGKMAN6nHOsi7m/UNJbXjaw+5ZeefX/lwrA9xqdUnlRcLuVyOVWryMXcpvJ8+8OBnZNvq1BJIydxPqNPttns8dLVjFHY5xr6Ht3Vv40Y5rmONx6LGtpDIsidq0ZJXEcY4saKQXCSsN+FNFmYKo4k1p8rX8gSK1wyLInap/pomuVV/qjea0wXCu31eBq78JvdVljd06n7l91Wn4K0tdLq+z0vdR8nnWXHIcfNvPCarXvPuNXZEEhG1bfoPbUU7x7VUOdNeUauq069XqqWduLnV3VLZsdz9NO/nVz/r/wBCl8NqeFW/t4jpCj0j21tOrjPHZsd9E4ZWU4kjPOoVtmw9wNWvmFpmi0rGDvkc7s0m15/FkjNXglOZoo2Vj27txqy8QVP3L7q+D40OkS7mI7OynHlMdvp5NxNdXHIZIzlZI0JBqNyNJZQcHl5l54TVbPIwRATlmOBwNfPIP1BU8tv8kTx7fXVja/STrv8Aw/zFXM8q5j07Ifnxr7dvJ7f4KmkQ5RgpHtFL4bUDKudlN0h3NQljcNGRnUKdOsk07tSLkGrSfSVjkh3Z/nrpthLECvFGfBrTJc2qN2NNXwo7TQyq0JHUvq5GrLxBU/cvuqyivpNkHHQYDJBp3sbiK7RTjmh/eimt1aM9KJjlajlHB1DeZdRxrqdoyABzr5nJ+1fM5P2oPegRxD6POS1SOlpJsU6EeMcBUMPpAZbv51HcW0RlLDS4X1VcWcls4lQjQO0ZzQkmt3jTQwyaN1a42x+Oh9Ktn5LOM8gppZr1dnGu8Rc276MTdFhvR+w18g7Y4PFvFfItGvOSYYqa1gGomNu9mxVrJJauqK4JJ5VNLDbPJGQuGHdVtbP1NxGMjVyNHTFcRnhqizv9lZlR4YyelJLxpUXcqjA+/wA//8QAJxABAAIBAwQBBQEBAQAAAAAAAQARITFRYUGBkfBxECCxwdFwMPH/2gAIAQEAAT8h/wB7DDM+TFVAG0lCOERlVWq4MesHApp/7y4sLxQ6Dde//RAVaDVZaD7AwW5oIGPQYI0Vu1y/eNyuUM6RKauQkq2e2TmEDIpv9Klq7GYUQhaKXAzmoNZZKL02aDpAAVa61vBbJa6DvLWR38oCoMYt8fRwCa2F8hpPfDnDme33xWMlTGOjPV7Zh7tWJHxhC08IwdSJh8mv2+k2+jpDlUDDlxA92ZdOTkiOD+O3fiCs36bOh2JpMFTs0eKe30I9xxF5DdEDCt86Qe7JRZ34ohQ6V0eo/pjh68O7OW/zKkUii4N1iNSleNs2dRnCYcN/Tie45nq9sccHiFvlHG6lZ/hLMR206AfDWj1IpFB1rGn2e02mMTsBzSg9LzKfKVAodZ7mOhQtOoW/2JQAkD1R+v5nslT+/lL8h/cZeg4lyWTv6kqkaJiozMjC/CbzKMEKmkzdfOEWmKkh5qtJ115jPhIRAboETPme45nq9sv4yvg3kol+LTAew/cLFUW5xWnchP0YHZL+xTGtWVT0v6ntf1GnJaPgmtCNjAFg4s9W5ZZXzF59cTAXmljofGO0LJU9XXwz0zNL+x1bXMoJBlUcx3/MdrqjQ+MMunoQ23TgRG71Qt/lEY3mGt8JkhvNOQB5yxX5u+qWZSo+ah5hMBKNNC+so35fOHhGD7PK0d2qGbIDUjrQ5WB/RFsGD/fP/9oADAMBAAIAAwAAABCSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSCCSSSSSSQSSSE0iSSSSSdoSSSWnYxQxxeGjeSSJyzgFCSf2jWSKOLiiKKverdSQ2+lGuL7EGs+SQCCACCQCAQCSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSf/8QAKBEBAAEDAQgCAwEBAAAAAAAAAREAITFRQWFxgZGhsfDB0SBw4RAw/9oACAEDAQE/EP32iuoTiJvNJGESIBcxcoNiK2STDspBD031RoyudiNqaRppjf8A8wVgoWUOVOlJuQuXUqJ0LAx+akNvkpBEMHhUyVy0TM0kLnyMX+ahLGKPaoBamjdBoIpMBmg5xtKUWOV2Gahx80Hos0nfoJH+SUOrByWJqXMa5OpJXvtShBuu813Pkr1N1T3xvg8pSgLLXHXH4+61rsjwpTE6TQ31PlCJ+Hc7d1CajZvmI61iaAcX+vmou3ucHHRk517G9XoN9G3bldBwGls/yoZg0BHmU9KvYIJ0HU+TreinZYjY6HcRO+1QsysAvHYDSjTYyF47ietPAhQNGEn1ua7lXc+SgkluOLBPLzSESNpg4sN6gxhugJ3ybHnRHMgpOsOfw91rTikCAu4UOx3X1WMyPIlg5H1Q6yW4rdrvSmCiQ+b5X5V6VC/T4oIoQPEo9hvoTD03jZTdQLRtoYXNionEi1RRRu422ieFmixGcICcJnO6o5DUn4aXQC6BQt0ruVdz5Kb+ysUBGLXTthoAaTsHVfFEEEFgQ8ZieTTZsk6Mfgq8AK6E17D9V6j9UqSXRAbybrpsreuEZeWwtUKZMHAsfdBYCmW/J1vzqG8mV7Mi9ttuc09JgCdk7qGSxxlwJpwucMCRt7ZJOtypeDbQcNXfg31m+NhqfejUmCTmAejZ5TWIEYueLFOFAcAHHL+0S9QBe/agZA2M7V3VNmfDG0tc3ifFByVpCTlhT4Ei2DdKWD2KzAqrxf35/8QAKBEBAAIABAUEAwEBAAAAAAAAAQARITFRsUFhcaHwIIGR0XDh8RAw/9oACAECAQE/EPz3ZxVNfErS8UG1jMU4bkCbPkYAe7yefP8A6XWMMIMR2GGS6RQba9YDhjTEpLrsw3ldV1EGmvD5whdYyqQZjLHKPWoOMoDXlAVKIk/Z9SoROX+VgjpntE6NdOPwzum0w06zY7TtIvQvljtMvXzT09ym82Y9h1bg6y1sD57k4tku+Uzmlvz2l6M8Trx85TYbky+jECY1dXX6lu0Oi4xe1SZmvnBjOcTd6H2y2wA4sLfFPMGGOQR54NM72bHadft0xwhNKU1zekt7XkQaYjhVno71FBo/TP6RM+R4sReY7Z/UYFhXdn23nvn8/wBJktIPcmT0YsUansy+tmsR4muIYby1Tg+N4O1WcFx2jlI8/wBInAism+DO9mx2hgYEweeMMQk6j8P3GNkTMcTzpCIyQfn0CHajOb7Tm+0PYWji/UQDTAyyJq7x6ucG2rKfbKIepVcy77SzcKY6dca8+sVbR/kMhQ4cXroTJ48HRmJm8zHaZmBq4ftgu20+6kbMAxuqYbTlfV645yyAPK9yWEI4r5awwyjD8+f/xAAoEAEBAAICAQQCAgEFAAAAAAABEQAhMUFREGFxgZGhIPBwMECxwdH/2gAIAQEAAT8Q/wAx3/caEMXTwBu2Sd4plnB1DT9UTFfDOLjoImlxmLVGhwYUkclqPQWiKKWjT/TJsaogHlzVD7ST4HN7Zd6RgArj5uqjAq9sDf8AM8SAADe7zffLraQHmFmGBygkDvtlSzKWz8txG8YUcXv94fPjAhRT3MooUuJEvkc7V4qaCvuofeSdRENTTmVPzkpVgn8q0GLRRj+dJ+2aj+AbeGcPs79NNLKj9iv2mJI5d1DtDF9GbdhmopWc7kQTXSdehZiVgHeSzpgJeFQ/eJChZY+VgPdP4/23n6HzILSiwiQnvh7koIrj90Dqn2JbDqcOMcRfmv8A0gh9Y3NeDgwL5/I5+tga9mNnlQNJC7Qg6DW1x6S6siUIS+y67mb0jGBulws2HGkY7qJCsUD7EAPUXIYa8J0nJEHaF1qld4bBtQvdwA+Yg+LvNcjbl3X3QR9095/fePQWWvNZFtV4UvkE4XA6iN1t84JtvZrDLjjpUQhDSe44bfQkQFQ7Es+v4a/3t8VrAEFAq0bQ+8VVgFcQT08USEeAW9894sNBPcnxfoXJBB5rdD4YffNqV+LV/wANgxRe9oH8PpXBAJpUUE70LkgvPr5W9e947wcFdQRysY6vDNaw7lBeRtAsipkVIyZ1NVXk7G4rOg4feHZyQUqSrWBGCfOf33j0FnWfVJ3sOlEdIpkmKWjSlm2dkc+MHYlbq1VOw62bEcekzyoID+f4SKdVSgC9uO7EEcQPhi/uyhu9qmtc4N1BBubEQRHsnjAJauf+siz4Ge7KKAupyvw5sPQ7cXwebxMJUWa7QNLmOEIQBGBB2iQEYQbHld8trf0fk3gIDEgmgFLmx28QM4s5AMSztDE7PcHA5UBo88k8IOFCZJids2/YPsxC0CQFldVYB0AdZpHoFA1ZjfwjCC5B0iZc8AToks7wDLKO5M4HLDZ84Pn9ZbS7CDVsfcUl5c25V+xAfgP4w8GQ8HpDx6TIeMgdek9Zk9IeMh49Jk/zJ//Z
    mediatype: image/jpeg
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - apps.baicell.com
          resources:
          - vbbus
          - vbbus/status
          - vbbus/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: baicell-helm-operator-controller-manager
      deployments:
      - name: baicell-helm-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.9
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=baicell-helm-operator
                image: quay.io/baicell/baicell-helm-operator:v01
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: baicell-helm-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: baicell-helm-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - baicell
  - vbbu
  - vran
  - vcu
  - vdu
  links:
  - name: Baicell Helm Operator
    url: https://baicell-helm-operator.domain
  maintainers:
  - email: wangzheng422@foxmail.com
    name: wangzheng
  maturity: alpha
  provider:
    name: baicell
    url: na.baicell.com
  version: 0.0.1
