apiVersion: apps.baicell.com/v1alpha1
kind: VBBU
metadata:
  name: vbbu-sample
spec:
  # Default values copied from <project_dir>/helm-charts/vbbu/values.yaml
  image:
    uri: "registry.ocp4.redhat.ren:5443/ocp4/du:v1-1623-wzh-01"

  service:
    nodePort: 31071

  net_attach_def:
    xeth:
      name: "host-device-du"
      config: '{
        "cniVersion": "0.3.0",
        "type": "host-device",
        "device": "xeth",
        "ipam": {
          "type": "host-local",
          "subnet": "192.168.160.0/24",
          "gateway": "192.168.160.254",
          "rangeStart": "192.168.160.1",
          "rangeEnd": "192.168.160.1"
        }}'
    enp:
      name: "host-device-du-ens"
      config: '{
        "cniVersion": "0.3.0",
        "type": "host-device",
        "device": "enp103s0f0",
        "ipam": {
          "type": "host-local",
          "subnet": "192.168.12.0/24",
          "rangeStart": "192.168.12.105",
          "rangeEnd": "192.168.12.106"
        }}'

  deploy:
    network: '[
            { "name": "host-device-du-ens",
              "interface": "veth11" },
            { "name": "host-device-du",
              "interface": "xeth" }
            ]'
    runtimeClassName: performance-wzh-performanceprofile

  nodeSelector: 
    node-role.kubernetes.io/master: ""
  
  
