apiVersion: apps/v1
kind: Deployment
metadata:
  name: du-deployment1
  labels:
    app: du-deployment1
spec:
  replicas: {{ .Values.deploy.replicas}}
  selector:
    matchLabels:
      app: du-pod1
  template:
    metadata:
      labels:
        app: du-pod1
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Values.deploy.network | quote }}
      # cpu-load-balancing.crio.io: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - fpga-driver
              topologyKey: "kubernetes.io/hostname"
      runtimeClassName: {{ .Values.deploy.runtimeClassName }}
      containers:
      - name: du-container1
        image: {{ .Values.image.uri | quote }}
        imagePullPolicy: IfNotPresent
        tty: true
        stdin: true
        env:
          - name: duNetProviderDriver
            value: "host-netdevice"
        command: ["/usr/sbin/init"]
        # - sleep
        # - infinity
        securityContext:
            privileged: true
            capabilities:
                add:
                - CAP_SYS_ADMIN
        volumeMounts:
          - mountPath: /hugepages
            name: hugepage
          - name: lib-modules
            mountPath: /lib/modules
          - name: src
            mountPath: /usr/src
          - name: dev
            mountPath: /dev
          - name: cache-volume
            mountPath: /dev/shm
          - name: license-volume
            mountPath: /baicell/lic
        resources:
          requests:
            cpu: {{ .Values.deploy.cpu}}
            memory: {{ .Values.deploy.memory }}
            hugepages-1Gi: {{ .Values.deploy.hugepages_1Gi }}
          limits:
            cpu: {{ .Values.deploy.cpu}}
            memory: {{ .Values.deploy.memory }}
            hugepages-1Gi: {{ .Values.deploy.hugepages_1Gi }}
      volumes:
        - name: hugepage
          emptyDir:
            medium: HugePages
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: src
          hostPath:
            path: /usr/src
        - name: dev
          hostPath:
            path: "/dev"
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.deploy.cache_memory }}
        - name: license-volume
          configMap:
            name: license.for.baicell
            items:
            - key: license
              path: license.lic
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}