apiVersion: v1
kind: Service
metadata:
  name: du-http 
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80 
    nodePort: {{ .Values.service.nodePort }}
  type: NodePort 
  selector:
    app: du-pod1